### ISSUE TITLE
Graph Sampler

### ISSUE THREAD

**Issue by liyuke65535** [ShengcaiLiao/QAConv#27]
thank u for ur work! I got 2 questions about Graph Sampling:
1. intuitively, it should work on normal ReID task.
2. The whole process is like: before training one epoch, the proposed sampler randomly select one img for each class, then computes a distmat for each img. The distmat represents distances between classes. So we can mine hardest samples in entire dataset, not a batch. But I didn't get where does "Graph" have connection to the process above.
Looking forward to your help

**Comment by ShengcaiLiao** [comment]
Hi,

Thank you for the interest.

1. Yes, it also helps the normal ReID task. For example, Table 2 in the paper shows that the proposed method outperforms our baseline on traditional single-dataset evaluation as well (gray areas).
2. Graph means that after computing the distmat, each class's top-k nearest neighbors are further obtained by ranking, as edges in a graph perspective. And so with this nearest neighboring graph, it is convenient to guide the data sampling for each batch.

**Comment by liyuke65535** [comment]
thanks!! I came up with an another puzzle: 
Is it reasonable to measure the distance between A class and B class via computing the distance of 2 images from A and B distinctly?

**Comment by ShengcaiLiao** [comment]
Good question. I would say, it is more efficient than reasonable. Data sampling is an auxiliary procedure to help learning, where accurate estimation of distances between classes would not be a must, or a critical thing that must be pursued. Given only one image per class, the learning benefits a lot from GS, with reasonable extra computational cost, that's it. 

Anyway, including more images should help, if the computational cost is not an issue. We did investigated the way of including more images per class, with improving performance but also with increasing computation. 

For further understanding, in ideal situation data sampling should estimate sample-to-sample distance, rather than the rough class-to-class distance, because intra-class variations could be large. But the computational cost will be even larger. For class-to-class relationships, class centers appear to be a more reasonable choice. However, due to large intra-class variations, limited on class centers may on the contrary lose flexibility of having some sample-to-sample estimation. For this regard, you are welcome to refer to the Appendix Section E of the paper for a further read.

So everything is a trade-off here.
